#!/usr/bin/env bash

num_failed=0
tests=0

init() {
  source .rosrc
  echo 'Running Tests'
}

add_fail() {
  ((tests_failed++))
}

summary() {
  echo ''
  if [[ ! $num_failed -eq 0 ]]; then
    chol "${num_failed}/${tests} Tests failed" --red
	else
    chol "${num_failed}/${tests} Tests failed" --green
  fi

	echo 'Done'
}

test_valid_master() {
  echo ''
  echo "Test $((++tests)): ${FUNCNAME[0]}"

  masters=('https://dfki@192.168.0.1:11311' 'https://dfki@uos.de' \
           'https://dfki@uos.de:11311' 'https://flamara@informatik.uos.de:11311' \
           'http' '')
  results=(0 1 0 0 1 1)
  
  if [[ ! ${#masters[@]} -eq ${#results[@]} ]]; then add_fail; chol 'invalid testing parameters' --red; return 1; fi

  for i in "${!masters[@]}"
  do
    valid_master "${masters[i]}" &> /dev/null
  
    if [[ $? -eq ${results[i]} ]]; then chol "TEST SUCCESS: ${masters[i]}" --green			
    else add_fail; chol "TEST FAIL   :${masters[i]}" --red; fi
  done
}

init

test_valid_master 

summary
