version: 2
jobs:
  indigo:
    docker:
      - image: ros:indigo-ros-base
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            chmod +x test/install/install_env.bash
            ./test/install/install_env.bash
      - run:
          name: Run Tests
          command: |
            chmod +x test/tests
            chmod +x test/test_indigo
            cd test && ./tests
  kinetic:
    docker:
      - image: ros:kinetic-ros-base
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            chmod +x test/install/install_env.bash
            ./test/install/install_env.bash
      - run:
          name: Run Tests
          command: |
            chmod +x test/tests
            chmod +x test/test_kinetic
            cd test && ./tests
  melodic:
    docker:
      - image: ros:melodic-ros-base
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            chmod +x test/tests
            chmod +x test/test_melodic 
            cd test && ./tests
      - run:
          name: Run Tests
          command: chmod +x test/tests && cd test && ./tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - indigo
      - kinetic
      - melodic
