version: 2
jobs:
  build:
    docker:
      - image: ros:kinetic-ros-base
    steps:
      - checkout
      - run:
        - name: Install Curl
        - command: 'sudo apt-get update; sudo apt-get install curl'
      -run:
        - name: Run Tests
        - command: chmod +x test/tests && cd test && ./tests
