version: 2
jobs:
  indigo:
    docker:
      - image: ros:indigo-ros-base
    steps:
      - run:
          name: Package Cache
          command: apt-get update -y
      - run:
          name: Install sudo
          command: apt-get install -y sudo
      - run:
          name: Install Curl
          command: sudo apt-get install -y curl
      - checkout
      - run:
          name: Run Tests
          command: chmod +x test/tests && cd test && ./tests
  kinetic:
    docker:
      - image: ros:kinetic-ros-base
    steps:
      - run:
          name: Install Dependencies
          command: chmod +x install/install_env.bash && ./install/install_env.bash
      - checkout
      - run:
          name: Run Tests
          command: chmod +x test/tests && cd test && ./tests
  melodic:
    docker:
      - image: ros:melodic-ros-base
    steps:
      - run:
          name: Package Cache
          command: apt-get update -y
      - run:
          name: Install sudo
          command: apt-get install -y sudo
      - run:
          name: Install Curl
          command: sudo apt-get install -y curl
      - checkout
      - run:
          name: Run Tests
          command: chmod +x test/tests && cd test && ./tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - indigo
      - kinetic
      - melodic
