version: 2
jobs:
  test:
    docker:
      - image: ros:kinetic-ros-base
    steps:
      - checkout
      - run:
          name: Install Curl
          command: sudo apt-get update && sudo apt-get install curl
      - run:
          name: Run Tests
          command: chmod +x test/tests && cd test && ./tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
